### PR TITLE
Support `merge_group` event natively

### LINKED ISSUE #432: Add support for merge_group event
### Type of issue

Feature Request

### Description

Our team uses [the merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) to serialize and validate changes on the default branch. I want to run ShellCheck when a change is added to the merge queue so that I can detect problems (e.g., introduced by a bad merge) before getting them merged to the default branch.

### Describe the solution you'd like

I tried creating a change, https://github.com/masaru-iritani/differential-shellcheck/pull/1.

Things I don't understand are:

- [Test suite job](https://github.com/masaru-iritani/differential-shellcheck/actions/runs/10059750771/job/27805695415?pr=1) failed due to "Error response from daemon: denied". Is there any permission I need for running it?
- `link_to_results` function is supposed to return a URL for querying the code scanning results, which I cannot see in this official repository or my fork. How can I understand what kind of URL to be generated?
- Is the merge queue (able to be) enabled in this repository so that workflows in this repository can test the functionality?

### PR DESCRIPTION
**Pull request by masaru-iritani**
# What

Support `merge_group` event natively.

# Why

Closes #432

Our team uses [the merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) to serialize and validate changes on the default branch. I want to run ShellCheck when a change is added to the merge queue so that I can detect problems introduced by a bad merge before pushing them to the default branch.

While I can configure the workflow to use "manual" triggering event with the base & head SHAs, it'd be convenient if the workflow natively support `merge_group`.

# How tested

Will see the CI test results.

# References

The definition of `merge_group` event.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group

### CODE REVIEW

**Comment by masaru-iritani** [comment]
> Please remove the Merge commit from the history.

Sure, I did.

**Comment by jamacku** [comment]
I have enabled the merge queue for the `main` branch. Can you also provide a workflow to run Differential ShellCheck in the merge queue? It would be very helpful. Thank you.

**Comment by masaru-iritani** [comment]
Thank you for enabling the merge queue, @jamacku!

I created another pull request #434 to illustrate how to run Differential ShellCheck on a `merge_group` event without this change.

**Comment by jamacku** [comment]
Thank you for enabling [running ShellCheck on merge_group](https://github.com/redhat-plumbers-in-action/differential-shellcheck/actions/runs/10176268729). Unfortunately, it seems that we hit an issue where if the branch doesn't contain any previous commits the base is referred to as `sha 0000000000000000000000000000000000000000`.

I think that the `github.event.merge_group.base_sha` is holding the same value.

**Review by jamacku — APPROVED** [review]
The code looks great. LGTM

Thank you for your contribution. I'm going to merge this PR. Only this repository is using `@main,` so unless we release a new version, nobody will be able to use this feature.

I plan to do some testing, and I'll try to find a way how to fix the issue mentioned in https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/433#issuecomment-2260179140

**Comment by masaru-iritani** [comment]
Thank you for incorporating this change and working on some tests!

> if the branch doesn't contain any previous commits the base is referred to as `sha 0000000000000000000000000000000000000000`.

Ah, I didn't thought about the case. Although I believe in most cases the workflow will be enabled for `merge_group` after using the merge queue at least once, the workflow may need to handle the case by making the check non-differential.

**Comment by jamacku** [comment]
So, I have verified that `merge_group` works as expected: 
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/actions/runs/10181482097/job/28161747618#step:5:1

The issue with `000...` is appearing `on push` (`triggering-event: push`) to merge queue temporary branch:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/actions/runs/10181482013/job/28161747328#step:5:928

For a workaround, you could provide a list of branches, etc. (e.g. `on: push ; branches: [ main ]`), or you can have the merge_group trigger in a separate workflow.

**Pull request merged**
