### PR TITLE
differential-shellcheck v1

### PR DESCRIPTION
**Pull request by jamacku**
- [x] Import of original code from [@fedora-sysv/initscripts](https://github.com/fedora-sysv/initscripts)
- [x] Containerization for code
- [x] declaration of `action.yml`
- [ ] documentation
- [ ] DOES IT WORK?

### CODE REVIEW

**Comment by mrc0mmand** [comment]
You have to create the first GH-action related branch directly in the "upstream" repo (i.e. directly in redhat-plumbers-in-action in this case), not a fork, otherwise GH will refuse to pick it up until it's merged.

**Comment by jamacku** [comment]
> You have to create the first GH-action related branch directly in the "upstream" repo (i.e. directly in redhat-plumbers-in-action in this case), not a fork, otherwise GH will refuse to pick it up until it's merged.

I know, I'm just tweaking it in fork (https://github.com/jamacku/differential-shellcheck/pull/9) and once it will have some shape, I'll merge it.

**Comment by mrc0mmand** [comment]
> > You have to create the first GH-action related branch directly in the "upstream" repo (i.e. directly in redhat-plumbers-in-action in this case), not a fork, otherwise GH will refuse to pick it up until it's merged.
> 
> I know, I'm just tweaking it in fork ([jamacku#9](https://github.com/jamacku/differential-shellcheck/pull/9)) and once it will have some shape, I'll merge it.

I see. I mean you can push it into a branch directly in this repo and then open a PR against master - that way you could test it in one place.

**Comment by jamacku** [comment]
> I see. I mean you can push it into a branch directly in this repo and then open a PR against master - that way you could test it in one place.

Yeah, let's do it then. :+1:

**Pull request merged**
